language: python
services:
    - docker
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  matrix:
#    - SCENARIO_NAME=py27-test
    - SCENARIO_NAME=test
install:
  - pip install tox-travis
  - pip install -e ${TRAVIS_BUILD_DIR}
script:
  - tox -e ${SCENARIO_NAME}
