version: 2
aliases:
  # SSH Deployment key for github Pushing,
  - &deploy_ssh_fingerprint "c8:23:a7:3d:53:15:5f:29:86:f1:e2:ca:3b:7a:0a:1b"

  # add the GitHub Deployment Key to the ssh-agent
  # @see https://circleci.com/docs/2.0/add-ssh-key/
  - &run_task_add_key
    add_ssh_keys:
      fingerprints:
        - *deploy_ssh_fingerprint
  - &run_task_add_gh_known_hosts
    run:
      name: Keyscan Github (HACK)
      command: |
        mkdir -p ${HOME}/.ssh
        chmod 700 ${HOME}/.ssh
        ssh-keyscan -H github.com >> ${HOME}/.ssh/known_hosts
        chmod 644 ${HOME}/.ssh/known_hosts

  # Configure git user settings
  # @see https://help.github.com/articles/setting-your-username-in-git/
  - &run_task_configure_git
    run:
      name: configure git set global settings
      command: |
        git config --global user.email "$GIT_AUTHOR_EMAIL"
        git config --global user.name "${CIRCLE_USERNAME}"

  # @see https://tox.readthedocs.io/en/latest/install.html
  # Install tox required system dependencies
  - &run_task_install_tox_dependencies
    run:
      name: install tox dependencies
      command: |
        sudo apt-get -qq update
        sudo apt install -y build-essential libssl-dev libpython-dev python python-pip
        virtualenv -p python3.6 ${HOME}/venv
        . ${HOME}/venv/bin/activate
        pip install tox

  - &run_task_prepare_github-release-manager
    run:
      name: install aktau/github-release manager
      command: |
        go get github.com/aktau/github-release

  # @see https://github.com/aktau/github-release
  # Used container for handle github release actions
  - &container_releasemanager
    docker:
      - image: circleci/golang:1.8

  # @see https://circleci.com/docs/2.0/language-python/
  # Used container for python based uilds
  - &container_python
    docker:
      - image: circleci/python:3.6.4

  # @see https://stedolan.github.io/jq/
  # used for better JSon Command Line parsing.
  - &run_task_prepare_jq
    run:
      name: install jq to path
      command: |
        sudo wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /usr/bin/jq
        sudo chmod +x /usr/bin/jq

  # Load the latest GitHub Release
  # Reuqired jq in the path
  # @see https://developer.github.com/v3/repos/releases/#get-the-latest-release
  - &run_task_load_latest_ghrelease
    run:
      name: Load the Latest GH Release
      command: |
        LAST_VERSION="$(curl https://${GITHUB_TOKEN}@api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest | jq -r '.tag_name' )"
        echo $LAST_VERSION > /tmp/workspaces/last_release.txt

  # extract the current version from the .bumpversion.cfg
  # save the extractd version to /tmp/workspaces/current_version.txt for later use
  # @see https://github.com/peritus/bumpversion
  - &run_task_load_current_version_bumpversion_cfg
    run:
      name: Load the Current Version from .bumpversion.cfg
      command: |
        CURRENT_VERSION="$(cat .bumpversion.cfg | grep current_version | sed -r s,"^.*=",, | sed 's/ //')"
        echo $CURRENT_VERSION > /tmp/workspaces/current_version.txt

  - &run_task_push_github_page
    run:
      command: |
        git clone $CIRCLE_REPOSITORY_URL --branch gh-pages --single-branch /tmp/ghpage
        cd /tmp/ghpage
        git rm -rf .
        ls -all /tmp/workspaces
        ls -all /tmp/workspaces/docs/tmp/html
        cp -r /tmp/workspaces/docs/tmp/html/. /tmp/ghpage
        git add -A
        git commit -m "[ci skip] Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
        git push origin gh-pages
jobs:
  publishghpage:
    <<: *container_python
    working_directory: /tmp/workspaces
    steps:
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - *run_task_push_github_page

  # generate a changelog from existing github commits/pull requests
  # using https://github.com/ferrarimarco/docker-github-changelog-generator as generate container
  # the container wraps https://github.com/github-changelog-generator/github-changelog-generator
  generate-changelog:
    machine: true
    working_directory: /tmp/workspaces/changelog
    steps:
      - *run_task_prepare_jq
      - *run_task_load_latest_ghrelease
      - run:
          name: generate CHANGELOG.md
          command: |
            LAST_VERSION="$(cat /tmp/workspaces/last_release.txt)"
            docker run -it --rm -v "$(pwd)":/usr/local/src/your-app ferrarimarco/github-changelog-generator:1.15.0.pre.beta --user ${CIRCLE_PROJECT_USERNAME} --project ${CIRCLE_PROJECT_REPONAME} --token ${GITHUB_TOKEN} --since-tag $LAST_VERSION --no-unreleased
      - store_artifacts:
          path: /tmp/workspaces/changelog
      - persist_to_workspace:
          root: /tmp/workspaces/changelog
          paths:
              - CHANGELOG.md

  finializebuild:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - attach_workspace:
          at: /tmp/workspaces
      - run:
          name: Push changes to github if release build
          command: |
            if [ -f /tmp/workspaces/release_build.txt ]; then
                releaseBranch="$(cat /tmp/workspaces/release_build.txt)"
                git push origin release/$releaseBranch
                git push origin ${CIRCLE_BRANCH}
            fi

  check_grade_up_build:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_configure_git
      - *run_task_install_tox_dependencies
      - checkout
      - run:
          name: check is release build
          command: |
            GIT_COMMIT_DESC=$(git log --format=%B -n 1 $CIRCLE_SHA1)
            if [[ $GIT_COMMIT_DESC =~ "GradeUP" ]] && [[ $CIRCLE_BRANCH == "develop" ]];
            then
              . ${HOME}/venv/bin/activate
              pip install bumpversion
              currentVersion=$(bumpversion --allow-dirty --dry-run --list release | grep new_version | sed -r s,"^.*=",,)
              bumpversion --commit release
              git checkout -b release/v$currentVersion-pre
              git checkout develop
              bumpversion --commit minor
              echo "v$currentVersion-pre" > /tmp/workspaces/release_build.txt
            else
               echo "classic build"
            fi
      - persist_to_workspace:
          root: /tmp/workspaces
          paths:
              - build/*
              - release_build.txt

  build:
    machine: true
    working_directory: /tmp/workspaces/build
    steps:
      - attach_workspace:
          at: /tmp/workspaces
      - run:
          name: install the project
          command: |
            sudo sh -c 'echo "deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu trusty main" >> /etc/apt/sources.list.d/python.list' && \
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F23C5A6CF475977595C89F51BA6932366A755776 && \
            sudo apt-get update -q && \
            sudo apt-get install -q -y curl git \
                python2.7 python2.7-dev libpython2.7-dev \
                python3.4 python3.4-dev libpython3.4-dev \
                python3.5 python3.5-dev libpython3.5-dev \
                python3.6 python3.6-dev libpython3.6-dev
      - *run_task_install_tox_dependencies
      - run:
          name: install the project
          command: |
            . ${HOME}/venv/bin/activate
            pip install -e ${CIRCLE_WORKING_DIRECTORY}
      - run:
          name: execute tox
          command: |
            . ${HOME}/venv/bin/activate
            tox
      - store_test_results:
          path: /tmp/workspaces/build/.tox/reports
      - store_artifacts:
          path: /tmp/workspaces/build/.tox/dist/
      - persist_to_workspace:
          root: /tmp/workspaces/build/.tox
          paths:
              - dist
              - docs/tmp/html/

  integrate_release:
    <<: *container_releasemanager
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_prepare_jq
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - attach_workspace:
          at: /tmp/workspaces
      - run:
          name: merge to master
          command: |
            git checkout master
            git merge ${CIRCLE_BRANCH}
            echo "merge to master"
      - run:
          name: create release tag
          command: |
            CURRENT_VERSION="$(cat /tmp/workspaces/build/version.txt)"
            git tag v$CURRENT_VERSION
            git push origin v$CURRENT_VERSION

  create_gh_release:
    <<: *container_releasemanager
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_prepare_jq
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - *run_task_prepare_github-release-manager
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_load_current_version_bumpversion_cfg
      - run:
          name: create github pre-release
          command: |
            CURRENT_VERSION="$(cat /tmp/workspaces/current_version.txt)"
            message="$(cat /tmp/workspaces/CHANGELOG.md)"
            github-release release \
                --user ${CIRCLE_PROJECT_USERNAME} \
                --repo ${CIRCLE_PROJECT_REPONAME} \
                --tag "v${CURRENT_VERSION}" \
                --name "v${CURRENT_VERSION}" \
                --description "${message}" \
                --pre-release
      - run:
          name: delete the release branch
          command: |
            git push origin master
            git push origin --delete ${CIRCLE_BRANCH}

workflows:
  version: 2
  build_and_test:
    jobs:
      - check_grade_up_build
      - build:
          requires:
            - check_grade_up_build
      - finializebuild:
          requires:
            - build
      - integrate_release:
          filters:
            branches:
              only:
                - /release\/v.*-pre/
          requires:
            - finializebuild
      - generate-changelog:
          requires:
            - integrate_release
      - create_gh_release:
          requires:
            - generate-changelog
      - publishghpage:
          requires:
            - build
          filters:
            branches:
              only:
                - master
